### ISSUE TITLE
graphics() returning incomplete information on Window 10

### ISSUE THREAD

**Issue by kyletmartinez** [sebhildebrandt/systeminformation#276]
**Describe the bug**
When testing multiple displays it appears the model and vendor information isn't populating for diplays[1]. It could be happening with additional displays but I don't have enough to test with. Its important to know that all other properties are updated correctly such as main, sizex, sizey, etc.

**To Reproduce**
I'm using the following code to test how systeminformation works.

```
const si = require("systeminformation");
si.graphics()
    .then(data => console.log(data))
    .catch(error => console.error(error));
```
**Current Output**
Here is just a small part of the output.

```
displays:
    0:
        model: "DELL U2715H(HDMI1)"
        vendor: "Dell Inc."
    1:
        model: "",
        vendor: ""
```

**Expected behavior**
I would expect model and vendor information to populate for every connected display.

**Environment (please complete the following information):**
 - systeminformation package version: 4.14.8
 - OS: Windows 10 Pro
 - Hardware: Custom built PC. Let me know if you need specifics.

**Additional context**

**Comment by kyletmartinez** [comment]
The model information appears to be returning correctly on macOS with multiple monitors. I suspect there is an issue with parsing the returned powershell data on Windows.

**Comment by sebhildebrandt** [comment]
@kyletmartinez need to check it. Will be at my windows working space next week.

**Comment by kyletmartinez** [comment]
So it turns out the culprit is `Get-WmiObject win32_desktopmonitor` which is unreliable post Windows Vista according to most of my research. For example, if two monitors are plugged into a single graphics card this particular utility only recognizes one. This is why most other attributes still update correctly with your current implementation.

However! Not all hope is lost. I believe we can still fetch/parse most of the information we need using a combination of PowerShell commands and linking items together with a shared property called `InstanceName`

`gwmi WmiMonitorID -Namespace root\wmi` provides properties such as `InstanceName`, `Active`, and `UserFriendlyName`. Somehow this can be combined with `gwmi WmiMonitorID -Namespace root\\wmi | ForEach-Object {($_.UserFriendlyName -notmatch 0 | foreach {[char]$_}) -join ''}` to parse the `UserFriendlyName` into a make/model.

`Get-CimInstance -Namespace root\wmi -ClassName WmiMonitorConnectionParams` will give us the `InstanceName` and `VideoOutputTechnology` where, for example, 5 is HDMI.

`Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.Screen]::AllScreens` still works correctly to provide bits per pixel, screen bounding information, and primary monitor information. You're already using this command.

I'm not sure if `Get-CimInstance -Namespace root\\wmi -ClassName WmiMonitorConnectionParams` is helpful but it provides that amazing `InstanceName` to learn `VideoOutputTechnology` but, like I said, I'm not sure if it is useful.

Hopefully you can use all this information to update that `workload` array and parse everything back together.

**Comment by kyletmartinez** [comment]
Quick copy paste code after I sorted out the weird single and double quote issues with child process and powershell.

```
const cli = require("child_process");
const si = require("systeminformation");

si.graphics()
    .then(data => console.log(data))
    .catch(error => console.log(error));

cli.exec("powershell.exe Get-CimInstance -Namespace root\\wmi -ClassName WmiMonitorBasicDisplayParams", (error, stdout, stderr) => {
    console.log(err);
    console.log(stdout);
});

cli.exec("powershell.exe gwmi WmiMonitorID -Namespace root\\wmi", (error, stdout, stderr) => {
    console.log(err);
    console.log(stdout);
});

cli.exec("powershell.exe \"gwmi WmiMonitorID -Namespace root\\wmi | ForEach-Object {($_.UserFriendlyName -notmatch 0 | foreach {[char]$_}) -join ''}\"", (error, stdout, stderr) => {
    console.log(err);
    console.log(stdout);
});

cli.exec("powershell.exe Get-CimInstance -Namespace root\\wmi -ClassName WmiMonitorConnectionParams", (error, stdout, stderr) => {
    console.log(err);
    console.log(stdout);
});

cli.exec("powershell.exe Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.Screen]::AllScreens", (error, stdout, stderr) => {
    console.log(err);
    console.log(stdout);
});```

**Comment by sebhildebrandt** [comment]
@kyletmartinez OK, so this is a good help. I made an investigation and ... as you can see in the code I am anyway using most of the powershell scripts. I now found a way to get Model, Manufacturer (using `gwmi WmiMonitorID`). Will provide a solution for that this weekend.

**Comment by sebhildebrandt** [comment]
@kyletmartinez you might try my changes in graphics.js (pushed here on github). I need to test this, but if you have a chance to give this a try, that would be great. We should now have proper results (model / vendor) per monitor.

**Comment by sebhildebrandt** [comment]
@kyletmartinez ... should be fixed. Version 4.14.16 just released.

**Comment by kyletmartinez** [comment]
@sebhildebrandt unfortunately I'm still not seeing the correct information with version 4.14.17. I noticed another ticket about monitor information and you asked for the user to run two commands, one in command line and one in power shell. I did the same if that is helpful.

COMMAND LINE

`Availability=8
Bandwidth=
Caption=DELL U2715H(HDMI1)
ConfigManagerErrorCode=0
ConfigManagerUserConfig=FALSE
CreationClassName=Win32_DesktopMonitor
Description=DELL U2715H(HDMI1)
DeviceID=DesktopMonitor1
DisplayType=
ErrorCleared=
ErrorDescription=
InstallDate=
IsLocked=
LastErrorCode=
MonitorManufacturer=Dell Inc.
MonitorType=DELL U2715H(HDMI1)
Name=DELL U2715H(HDMI1)
PixelsPerXLogicalInch=96
PixelsPerYLogicalInch=96
PNPDeviceID=DISPLAY\DELD067\5&amp;382CED2F&amp;0&amp;UID4353
PowerManagementCapabilities=
PowerManagementSupported=
ScreenHeight=
ScreenWidth=
Status=OK
StatusInfo=
SystemCreationClassName=Win32_ComputerSystem
SystemName=DESKTOP-AINIHS3`

POWER SHELL

`DEL|D067|DELL U715H|H7YCC6B814S|DISPLAY\DELD067\5&382ced2f&0&UID4353_0
DEL|D067|DELL U715H|H7YCC6B814YS|DISPLAY\DELD067\5&382ced2f&0&UID4354_0`
