### ISSUE TITLE
si.diskLayout on CentOS 7 (systemd-based)

### ISSUE THREAD

**Issue by paul-bell** [sebhildebrandt/systeminformation#55]
Hi Sebastian,

Using 3.17.2 on CentOS 7 si.diskLayout(cb) returns an empty (pending) promise which is never fulfilled, e.g.,

```
[root@localhost ecxmon]# node
> var si = require('systeminformation')
undefined
> si.diskLayout(function(d) {console.log(d)})
Promise { <pending> }
> []
```

FWIW si.memLayout() works. I haven't tried on a non-systemd platform.

Thanks.

-Paul

**Comment by sebhildebrandt** [comment]
Hi, `diskLayout()` was introduced in version 3.23.0, so it should not be available in 3.17.2 ... but anyway, I will check the code an post a fix tomorrow.

**Comment by paul-bell** [comment]
So sorry; I thought I'd recently downloaded latest version. Apparently not.

But I just now obtained 3.23.6 and I think problem still occurs.

Cordially,

Paul

**Comment by sebhildebrandt** [comment]
Hi again,

can't reproduce problem on my machines (systemd, non-systemd). Can you try once again using latest version (3.23.7 published today) and try callback AND promise style:

```
const si = require('systeminformation')
si.diskLayout(function(d) {console.log(d)})
```

and 

```
const si = require('systeminformation')
si.diskLayout.then(d => {
    console.log(d);
})
```
Thank you so much

**Comment by paul-bell** [comment]
Tried both against .7; neither worked.

```
> si.diskLayout(function(d) {console.log(d)})
Promise { <pending> }
> []

> si.diskLayout().then(d => { console.log(d);})
Promise { <pending> }
> []

.exit

[root@localhost ecxmon]# npm ls systeminformation
ECX_Monitor@0.1.0 /home/ecxcc/ecxmon
└── systeminformation@3.23.7
```

**Comment by sebhildebrandt** [comment]
Ahhh, I guess, the thing is, that this is not a problem of a pending (not fulfilled) promise. It simply returns an empty array []. This might be caused, because `lshw -class disk` is not returning valid information. Maybe you can post the result of the upper command here. I will check it then and try to find a fix. But: be patient, as I will have very few time for the next 2 weeks, maybe I will post a fix afterwards. OK?

**Comment by paul-bell** [comment]
Bingo; right you are!

There is no lshw command, neither on CentOS 6 or 7.

I will install it and try again.

**Comment by paul-bell** [comment]
Installed lshw on CentOS 7.

Via si:

```
> si.diskLayout(function(d) {console.log(d)})
Promise { <pending> }
> cat: /sys/block/cdrom/queue/rotational: No such file or directory
[]
```

Via 'lshw -class disk':
```
[root@localhost ecxmon]# lshw -class disk
  *-cdrom
       description: DVD-RAM writer
       physical id: 0.0.0
       bus info: scsi@1:0.0.0
       logical name: /dev/cdrom
       logical name: /dev/sr0
       capabilities: audio cd-r cd-rw dvd dvd-r dvd-ram
       configuration: status=open
  *-disk:0
       description: SCSI Disk
       physical id: 0.0.0
       bus info: scsi@2:0.0.0
       logical name: /dev/sda
       size: 20GiB (21GB)
       capabilities: partitioned partitioned:dos
       configuration: logicalsectorsize=512 sectorsize=512 signature=000b8a58
  *-disk:1
       description: SCSI Disk
       physical id: 0.1.0
       bus info: scsi@2:0.1.0
       logical name: /dev/sdb
       serial: 7lUfI1-nCIA-ebGR-5EVA-YHND-x8Kt-AtH88n
       size: 20GiB (21GB)
       capacity: 20GiB (21GB)
       capabilities: lvm2
       configuration: logicalsectorsize=512 sectorsize=512
  *-disk:2
       description: SCSI Disk
       physical id: 0.2.0
       bus info: scsi@2:0.2.0
       logical name: /dev/sdc
       serial: 4oXMZc-uIN4-36mP-N8Kb-uQj0-KOFM-ENFTTk
       size: 20GiB (21GB)
       capacity: 20GiB (21GB)
       capabilities: lvm2
       configuration: logicalsectorsize=512 sectorsize=512
  *-disk:3
       description: SCSI Disk
       physical id: 0.3.0
       bus info: scsi@2:0.3.0
       logical name: /dev/sdd
       size: 30GiB (32GB)
       configuration: logicalsectorsize=512 sectorsize=512 signature=0004f2d3
  *-disk:4
       description: SCSI Disk
       physical id: 0.4.0
       bus info: scsi@2:0.4.0
       logical name: /dev/sde
       size: 16GiB (17GB)
       capabilities: gpt-1.00 partitioned partitioned:gpt
       configuration: guid=abd1eca5-c7cf-f649-bb0e-877b901db00d logicalsectorsize=512 sectorsize=512
  *-disk:5
       description: SCSI Disk
       physical id: 0.5.0
       bus info: scsi@2:0.5.0
       logical name: /dev/sdf
       size: 16GiB (17GB)
       capabilities: gpt-1.00 partitioned partitioned:gpt
       configuration: guid=d9fea711-8d5e-a148-a635-c62e2ffb8188 logicalsectorsize=512 sectorsize=512
  *-disk:6
       description: SCSI Disk
       physical id: 0.6.0
       bus info: scsi@2:0.6.0
       logical name: /dev/sdg
       size: 16GiB (17GB)
       capabilities: gpt-1.00 partitioned partitioned:gpt
       configuration: guid=748fe734-8c9c-6949-b264-9a76cd09701e logicalsectorsize=512 sectorsize=512
  *-disk:7
       description: SCSI Disk
       physical id: 0.8.0
       bus info: scsi@2:0.8.0
       logical name: /dev/sdh
       size: 16GiB (17GB)
       capabilities: gpt-1.00 partitioned partitioned:gpt
       configuration: guid=da634648-0cf8-9542-8558-5ff3b7c39819 logicalsectorsize=512 sectorsize=512
```

**Comment by sebhildebrandt** [comment]
Ok. Thank you. Then I know wat I need to do. Will take a while.

**Comment by paul-bell** [comment]
Thank you, Sebastian; no rush.

-Paul

**Comment by Bartozzz** [comment]
Same issue on _64bit Mac OS X 10.12.5 16F73_.

**Comment by sebhildebrandt** [comment]
@Bartozzz : can you provide a little more information about your problem here (as the original bug is related to CentOS)? Are you getting also en empty array []? If yes, can you post the output of the following command (in the command line): `system_profiler SPSerialATADataType`

Thank you in advance

**Comment by Bartozzz** [comment]
Yes, I am getting an empty array:

```bash
$ node                   
> var si = require( "systeminformation" );
undefined
> si.diskLayout( data => console.log( data ) );
Promise {
  <pending>,
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
> []
```

#### `system_profiler SPSerialATADataType` output:

```
SATA/SATA Express:

    Apple SSD Controller:

      Vendor: Apple
      Product: SSD Controller
      Physical Interconnect: PCI
      Link Width: x2
      Link Speed: 5.0 GT/s
      Description: AHCI Version 1.00 Supported

        APPLE SSD SD0128F:

          Capacity: 121,33 GB (121 332 826 112 bytes)
          Model: APPLE SSD SD0128F                       
          Revision: A223321 
          Serial Number: 1437FC402321
          Native Command Queuing: Yes
          Queue Depth: 32
          Removable Media: No
          Detachable Drive: No
          BSD Name: disk0
          Medium Type: Solid State
          TRIM Support: Yes
          Partition Map Type: GPT (GUID Partition Table)
          S.M.A.R.T. status: Verified
          Volumes:
            EFI:
              Capacity: 209,7 MB (209 715 200 bytes)
              File System: MS-DOS FAT32
              BSD Name: disk0s1
              Content: EFI
              Volume UUID: 0E239BC6-F960-3107-89CF-1C97F78BB46B
            disk0s2:
              Capacity: 120,47 GB (120 472 952 832 bytes)
              BSD Name: disk0s2
              Content: Apple_CoreStorage
            Recovery HD:
              Capacity: 650 MB (650 002 432 bytes)
              File System: Journaled HFS+
              BSD Name: disk0s3
              Content: Apple_Boot
              Volume UUID: F1391AA2-221F-34C1-BACA-7C7544608580
```

#### `system_profiler SPNVMeDataType` output:

Nothing is returned.

**Comment by sebhildebrandt** [comment]
@Bartozzz: OK, I think I now, where the problem is ;-) Thank you so much! Very helpful! 
Will provide an update for the OSX problem end of this week.

**Comment by sebhildebrandt** [comment]
Both problems (CentOS - or more specifically CDROM, as well es OSX) are fixed now. Just provided an update on that. @paul-bell , @Bartozzz can you both check it also on your side? Thank you so much!

**Comment by Bartozzz** [comment]
Everything working fine on macOS, thanks a lot. 😄

**Comment by paul-bell** [comment]
Hi Sebastian,

I somehow missed your "please check" request from last week and today just happened to revisit this issue. Still broken, I think:

I installed lshw on Centos 7. Its _lshw -class disk_ output is visible earlier in this thread. Then did:

```
> var si = require('systeminformation')
undefined
> si.diskLayout(function(d) {console.log(d)} )
Promise { <pending> }
> cat: /sys/block/cdrom/queue/rotational: No such file or directory
[]
```
I doubt it's germane, but note the 'undefined' after the require statement. It appears in a very dark shade of gray and is nearly invisible against the console's black background.

si version is 3.30.1

Please let me know how I can help; thanks.

-Paul

**Comment by sebhildebrandt** [comment]
Thank you so much, I will once again recheck my code. Will come back as soon as I have an idea ...
